spring:
  data:
    mongodb:
      port: 27017
      database: limemessenger
  mail:
    host: smtp.gmail.com
    port: 587
    username: store
    password: passwordappgmail
    properties:
      mail:
        smtp:
          debug: true
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
server:
  port: 3008
logging:
  level:
    org.springframework.security: DEBUG
email:
  server: gmail.com
  sendername: Store
  emailcco: test@gmail.com